import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Modal from "./components/modals/Modal";

const poppins = Poppins({
  variable: "--font-geist-sans",
  weight: ["100", "200", "300", "400", "500"],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "DjangoBnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const content = (
    <p>yo</p>
  )


  return (
    <html
      lang="en"
      className={`${poppins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <div className="pt-32">
          {children}
        </div>

        <Modal label='modal test' content={content} isOpen={true} />

      </body>
    </html>
  );
}
